context('Game 2',() => {
    beforeEach(() => {
        cy.viewport(2000, 1000)
        cy.visit('nmhung0519.github.io/CNPM/Sources/Game2.html')
    })
    it("Start", function() {
        cy.get('#start_button').click().should('be.visible')
        cy.wait(4500)
        cy.get('body').type('3')
        cy.get('#game_display').contains('3').should(($3) => {
            expect($3).to.have.css('display', 'block')
        })
        cy.wait(1000)
        cy.get('body').type('4')
        cy.get('#game_display').contains('4').should(($3) => {
            expect($3).to.have.css('display', 'block')
        })
        cy.wait(1000)
        cy.get('body').type('5')
        cy.get('#game_display').contains('5').should(($3) => {
            expect($3).to.have.css('display', 'block')
        })
        cy.wait(1000)
        cy.get('body').type('7')
        cy.get('#game_display').contains('6').should(($3) => {
            expect($3).to.have.css('display', 'none')
        })
        cy.get('#dialog').should(($dialog) =>{
            expect($dialog).to.have.css('display', 'block')
        })
        cy.get('#dialog').contains('After 5 comes 6').should('be.visible')
        cy.wait(1000)
        cy.get('body').type('6')
        cy.get('#game_display').contains('6').should(($3) => {
            expect($3).to.have.css('display', 'block')
        })
        cy.get('#dialog').should(($dialog) => {
            expect($dialog).to.have.css('display', 'none')
        })
    })
    it ("Correct", function() {
        cy.get("#start_button").click()
        cy.wait(4500)
        cy.wait(1000)
        cy.get('body').type('3')
        cy.wait(1000)
        cy.get('body').type('4')
        cy.wait(1000)
        cy.get('body').type('5')
        cy.wait(1000)
        cy.get('body').type('6')
        cy.wait(1000)
        cy.get('body').type('7')
        cy.wait(1000)
        cy.get('body').type('8')
        cy.wait(1000)
        cy.get('body').type('9')
        cy.wait(1000)
        cy.get('body').type('9')
        cy.wait(1000)
        cy.get('#start_button').should('be.visible')
        cy.get("#start_button").click().should('be.not.visible')
        cy.get('#big_box').should('be.visible')
        cy.get('body').type('2')
        cy.get('#big_box').should('be.not.visible')
        cy.get('#answer').should('be.visible')
    })
    it ("Incorrect", function() {
        cy.get("#start_button").click()
        cy.wait(4500)
        cy.wait(1000)
        cy.get('body').type('3')
        cy.wait(1000)
        cy.get('body').type('4')
        cy.wait(1000)
        cy.get('body').type('5')
        cy.wait(1000)
        cy.get('body').type('6')
        cy.wait(1000)
        cy.get('body').type('7')
        cy.wait(1000)
        cy.get('body').type('8')
        cy.wait(1000)
        cy.get('body').type('9')
        cy.wait(1000)
        cy.get('body').type('9')
        cy.wait(1000)
        cy.get('#start_button').click()
        cy.wait(500)
        cy.get('body').type('3')
        cy.get('#big_box').should('be.not.visible')
        cy.get('#answer').should('be.visible')
        cy.get('#wrong_line').should('be.visible')
    })
})